apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-micro-gateway.fullname" . }}-config
  labels:
    {{- include "spring-micro-gateway.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val }}
{{- end}}
