apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-micro-session
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/coolexplorer/spring-micro-argocd.git
    targetRevision: main
    path: spring-micro-session
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true