apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-micro-auth
  namespace: argocd
spec:
  project: spring-micro-auth
  source:
    repoURL: https://github.com/coolexplorer/spring-micro-argocd.git
    targetRevision: HEAD
    path: spring-micro-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: default