apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-micro-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/coolexplorer/spring-micro-argocd.git
    targetRevision: main
    path: spring-micro-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: default